const QUERY_KEY = {
  PROGRAM: {
    LIST: "PROGRAM_LIST",
    GIFT_LIST: "PROGRAM_GIFT_LIST",
    CUSTOMER_LIST: "PROGRAM_CUSTOMER_LIST",
    CUSTOMER_LUCKY_LIST: "PROGRAM_CUSTOMER_LUCKY_LIST",
    EXTRA_NUMBER_LIST: "EXTRA_NUMBER_LIST",
  },
};

export default QUERY_KEY;
